codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false

flags:
  backend:
    paths:
      - backend/app/
    carryforward: true
