---
name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    # renovate: datasource=github-tags depName=DevSecNinja/.github
    uses: DevSecNinja/.github/.github/workflows/lint.yml@7f2abdd838a855dba31a2b2de6358529fdcef09d # v1.8.0
    permissions:
      contents: read
      security-events: write
    with:
      # renovate: datasource=github-releases depName=jdx/mise
      mise-version: "2026.6.3"
      lint-dprint: false
      lint-yamlfmt: false
      lint-yamllint: false
      lint-checkov: false
      lint-trivy: false
      lint-config-drift: false
