---
name: "Run Todo to Issue"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  run:
    name: "Run Todo to Issue"
    runs-on: "ubuntu-24.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@37bb7b56e58569ef273b60678048030a7f0c261a" # v5.1.15
        with:
          AUTO_ASSIGN: false
